FROM golang:alpine as builder

WORKDIR /app

COPY . .

RUN go build -o main .

FROM scratch

ENV LOG_FILE_LOCATION=/logs/app.log

COPY --from=builder /app/main /app/main

VOLUME ["/logs"]

EXPOSE 8080

CMD ["/app/main"]